::python module3.py DC
::python module3.py NewHampshire
::python module3.py NewJersey
::python module3.py NewMexico
::python module3.py NorthCarolina
::python module3.py NorthDakota
::python module3.py RhodeIsland
::python module3.py SouthDakota
::python module3.py SouthCarolina
python module3.py Hawaii
python module3.py Texas
python module3.py California
python module3.py NewYork
python module3.py Pennsylvania