python module4.py Nebraska
python module4.py Nevada
python module4.py NewHampshire
python module4.py NewJersey
python module4.py NewMexico
python module4.py NewYork
python module4.py NorthCarolina
python module4.py NorthDakota
python module4.py Ohio
python module4.py Oregon
python module4.py Oklahoma
python module4.py RhodeIsland
python module4.py Pennsylvania
python module4.py SouthCarolina
python module4.py SouthDakota
python module4.py Tennessee
python module4.py Texas
python module4.py Utah
python module4.py Vermont
python module4.py Virginia
python module4.py Washington
python module4.py WestVirginia
python module4.py Wisconsin
python module4.py Wyoming