python module4.py Alabama
python module4.py Alaska
python module4.py Arizona
python module4.py Arkansas
python module4.py California
python module4.py Colorado
python module4.py Connecticut
python module4.py DC
python module4.py Delaware
python module4.py Florida
python module4.py Georgia
python module4.py Hawaii
python module4.py Idaho
python module4.py Illinois
python module4.py Indiana
python module4.py Iowa
python module4.py Kansas
python module4.py Kentucky
python module4.py Louisiana
python module4.py Maine
python module4.py Maryland
python module4.py Massachusetts
python module4.py Michigan
python module4.py Minnesota
python module4.py Mississippi
python module4.py Missouri
python module4.py Montana